# Configuration Easypanel pour OSINTReport
# Version simplifiée pour Easypanel

version: '3.8'

services:
  # === PostgreSQL ===
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-osint_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-osint_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - osintreport

  # === Meilisearch ===
  meilisearch:
    image: getmeili/meilisearch:v1.5
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch-data:/meili_data
    networks:
      - osintreport

  # === Backend API ===
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://${POSTGRES_USER:-osint_admin}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-osint_db}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      COOKIE_SECRET: ${COOKIE_SECRET}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      FRONTEND_URL: ${FRONTEND_URL}
      MEILI_HOST: http://meilisearch:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_FIRST_NAME: ${ADMIN_FIRST_NAME:-Admin}
      ADMIN_LAST_NAME: ${ADMIN_LAST_NAME:-System}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_SECURE: ${SMTP_SECURE:-false}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL:-}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME:-OSINTReport}
    volumes:
      - backend-uploads:/app/uploads
      - backend-logs:/app/logs
    depends_on:
      - postgres
      - meilisearch
    networks:
      - osintreport
    expose:
      - "4000"

  # === Frontend ===
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - osintreport
    ports:
      - "80:8080"

volumes:
  postgres-data:
  meilisearch-data:
  backend-uploads:
  backend-logs:

networks:
  osintreport:
    driver: bridge
