# Configuration EasyPanel pour OSINTReport

# Ce fichier peut être utilisé comme référence pour configurer votre projet sur EasyPanel
# EasyPanel supporte le déploiement via GitHub avec Docker Compose

name: osintreport
services:
  - type: postgres
    name: postgres
    image: postgres:16-alpine
    volumes:
      - name: postgres-data
        mount: /var/lib/postgresql/data
    env:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    
  - type: app
    name: meilisearch
    image: getmeili/meilisearch:v1.5
    volumes:
      - name: meilisearch-data
        mount: /meili_data
    env:
      MEILI_MASTER_KEY: $MEILI_MASTER_KEY
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: "true"
    
  - type: app
    name: backend
    source:
      type: github
      repo: Ch4rC0M1n0U/OSINTReport
      path: backend
      branch: main
    build:
      type: dockerfile
      dockerfile: Dockerfile
    domains:
      - name: api.votredomaine.com
    env:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: $DATABASE_URL
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRES_IN: 7d
      COOKIE_SECRET: $COOKIE_SECRET
      COOKIE_DOMAIN: $COOKIE_DOMAIN
      FRONTEND_URL: $FRONTEND_URL
      MEILI_HOST: http://meilisearch:7700
      MEILI_MASTER_KEY: $MEILI_MASTER_KEY
      ADMIN_EMAIL: $ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD
      ADMIN_FIRST_NAME: $ADMIN_FIRST_NAME
      ADMIN_LAST_NAME: $ADMIN_LAST_NAME
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_USER: $SMTP_USER
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_FROM_EMAIL: $SMTP_FROM_EMAIL
    volumes:
      - name: backend-uploads
        mount: /app/uploads
      - name: backend-logs
        mount: /app/logs
    
  - type: app
    name: frontend
    source:
      type: github
      repo: Ch4rC0M1n0U/OSINTReport
      path: frontend
      branch: main
    build:
      type: dockerfile
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: $VITE_API_BASE_URL
    domains:
      - name: votredomaine.com
      - name: www.votredomaine.com
    ports:
      - 8080:80

volumes:
  - postgres-data
  - meilisearch-data
  - backend-uploads
  - backend-logs
